- name: Creating {{app_user}} user
  become: true
  user: name={{ app_user }} state=present

- name: Creating {{ app_group }} group
  become: true
  group: name={{ app_group }} state=present

- name: Creating directory structure
  become: true
  file: path={{ app_path }} state=directory owner={{ app_user }} group={{ app_group }}

- name: Deploying our Application
  become: true
  become_user: "{{ app_user }}"
  copy: src={{ source_code }} dest={{ app_path }}/{{bin_name}} owner={{ app_user }} group={{ app_group }} mode=0644
